CONNECT 'DataBase\acosa.fdb' USER 'SYSDBA' PASSWORD 'masterkey';
INSERT INTO TBL_PROV_DFISCALES (ID, CODIGO, NOMBRE, RFC, DIRECCION, ACTIVO, FECHA_REGISTRO) VALUES ('prov-001','P001','Proveedor Prueba','RFC123','Direccion de prueba',1,'2026-01-14');
COMMIT;
EXIT;
